version: '3'

services:
  
  api:
    image: book-store-api:latest
    ports:
      - "7223:80"
    depends_on:
      - postgres
      - minio
    environment:
      - ConnectionString:Host=postgres;User ID =admin;Password=admin;Port=5432;Database=books;Integrated Security=true;Pooling=true;

  auth:
    image: book-store-auth:latest
    ports:
      - "7198:80"
    depends_on:
      - postgres

  profiles:
    image: profiles:latest
    ports:
      - "7034:80"
    depends_on:
      - mssql
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=SpikePrototype2016!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8082:80"

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: asdasdj132sd1sasd12edasdqw212ed123ad1s12
      MINIO_ROOT_PASSWORD: asdaasasdasddasdj132sd1sasd12edasdqw212ed123ad1s12asd1231nfasd
    volumes:
      - ./volumes/minio/.minio/data:/export
      - ./volumes/minio/.minio/config:/root/.minio

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      # RabbitMq instance
      - "5672:5672"
      # Web interface
      - "15672:15672"

  azurite-db:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-db
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
