version: '3'

services:
  
  bookstore:
    image: book-store-api
    ports:
      - "7223:80"
    depends_on:
      - postgres
      - azurite-db
      - rabbitmq
    environment:
      - ConnectionString:Host=postgres;User ID =admin;Password=admin;Port=5432;Database=books;Integrated Security=true;Pooling=true;

  auth:
    image: book-store-auth:latest
    ports:
      - "7198:80"
    depends_on:
      - postgres
      - rabbitmq

  profiles:
    image: profiles:latest
    ports:
      - "7034:80"
    depends_on:
      - mssql
      - rabbitmq
  
  requests:
    build:
      context: .
      dockerfile: Requests/Dockerfile
    ports:
      - "7024:80"
    depends_on:
      - mongo
      - azurite-db
      - rabbitmq

  comments:
    build:
      context: .
      dockerfile: Comments/Dockerfile
    ports:
      - "7045:80"
    depends_on:
      - mongo
      - rabbitmq

  email:
    build:
      context: .
      dockerfile: EmailService/Dockerfile
    ports:
      - "7265:80"
    depends_on:
      - rabbitmq

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=SpikePrototype2016!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8082:80"

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      # RabbitMq instance
      - "5672:5672"
      # Web interface
      - "15672:15672"

  azurite-db:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-db
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.7.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.watcher.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: kibana:8.7.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=https://localhost:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
