version: '3'

services:
  
  bookstore:
    build:
      context: .
      dockerfile: BookStore/Dockerfile
    ports:
      - "7025:80"
    depends_on:
      - postgres
      - azurite-db
      - rabbitmq
    
  auth:
    build:
      context: .
      dockerfile: Auth/Dockerfile
    ports:
      - "7198:80"
    depends_on:
      - postgres
      - rabbitmq

  profiles:
    build:
      context: .
      dockerfile: Profiles/Dockerfile
    labels:
      - mssql=mssql
    ports:
      - "7034:80"
    depends_on:
      - mssql
      - rabbitmq
  
  requests:
    build:
      context: .
      dockerfile: Requests/Dockerfile
    ports:
      - "7024:80"
    depends_on:
      - azurite-db
      - rabbitmq
      - mongo

  comments:
    build:
      context: .
      dockerfile: Comments/Dockerfile
    ports:
      - "7045:80"
    depends_on:
      - rabbitmq
      - mongo

  email:
    build:
      context: .
      dockerfile: EmailService/Dockerfile
    ports:
      - "7265:80"
    depends_on:
      - rabbitmq

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "change_this_password"
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: 1433
    ports:
        - 1442:1433
    volumes:
      - ./mssql_init_database.sql:/init.sql

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  mongo:
    image: mongo:latest
    ports:
      - 27018:27017

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8082:80"

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      # RabbitMq instance
      - "5673:5672"
      # Web interface
      - "15672:15672"
    restart: on-failure

  azurite-db:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-db
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
