version: '3'

services:
  
  api:
    image: book-store:1.0
    ports:
      - "7223:80"
    depends_on:
      - postgres
      - minio

  auth:
    image: book-store-auth:latest
    ports:
      - "7198:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8082:80"

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: asdasdj132sd1sasd12edasdqw212ed123ad1s12
      MINIO_ROOT_PASSWORD: asdaasasdasddasdj132sd1sasd12edasdqw212ed123ad1s12asd1231nfasd
    volumes:
      - ./volumes/minio/.minio/data:/export
      - ./volumes/minio/.minio/config:/root/.minio

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      # RabbitMq instance
      - "5672:5672"
      # Web interface
      - "15672:15672"