version: '3'

networks:
  my-network:
    driver: bridge

services:
  
  api:
    image: book-store:1.0
    ports:
      - "7223:80"
    networks: 
      - my-network

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "books"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    networks:
      - my-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8082:80"
    networks:
      - my-network

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: asdasdj132sd1sasd12edasdqw212ed123ad1s12
      MINIO_ROOT_PASSWORD: asdaasasdasddasdj132sd1sasd12edasdqw212ed123ad1s12asd1231nfasd
    volumes:
      - ./volumes/minio/.minio/data:/export
      - ./volumes/minio/.minio/config:/root/.minio
    networks:
      - my-network
